### ISSUE TITLE
TypeError while syncing

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [Wellenline/auddly-server#10]
```
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:127:13)
    at Object.request (https.js:301:10)
    at RedirectableRequest._performRequest (/app/node_modules/follow-redirects/index.js:169:24)
    at new RedirectableRequest (/app/node_modules/follow-redirects/index.js:66:8)
    at Object.wrappedProtocol.request (/app/node_modules/follow-redirects/index.js:307:14)
    at dispatchHttpRequest (/app/node_modules/axios/lib/adapters/http.js:141:25)
    at new Promise (<anonymous>)
    at httpAdapter (/app/node_modules/axios/lib/adapters/http.js:18:10)
    at dispatchRequest (/app/node_modules/axios/lib/core/dispatchRequest.js:59:10)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

I think this is what is causing several artists not to appear for me.

**Comment by MihkelBaranov** [comment]
Should be fixed in the latest release
