### ISSUE TITLE
Sync failing

### ISSUE THREAD

**Issue by nebula-it** [Wellenline/auddly-server#21]
A modern music setup was lacking from my self hosted setup and this seems to be really promising so Thank you for such amazing project. Now onto the issue:
The sync is failing with following error:
```
waveline-api | (node:25) UnhandledPromiseRejectionWarning: Error: End-Of-File
waveline-api |     at /app/node_modules/strtok3/lib/FileTokenizer.js:52:23
waveline-api |     at invokeCallback (/app/node_modules/es6-promise/dist/es6-promise.js:408:15)
waveline-api |     at publish (/app/node_modules/es6-promise/dist/es6-promise.js:391:7)
waveline-api |     at flush (/app/node_modules/es6-promise/dist/es6-promise.js:128:5)
waveline-api |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
waveline-api | (node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch b
lock, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=st
rict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
waveline-api | (node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
Node.js process with a non-zero exit code.
```
This is using the newest updates, let me know if I can assist in any way.
Cheers

**Comment by MihkelBaranov** [comment]
Hmm, are you running inside docker? I'm guessing it's failing to read some file for metadata

**Comment by nebula-it** [comment]
Yes, it inside docker. I'm guessing one of the file has bad metadata. Can this be set to more verbose so I can find which file is causing the issue.

**Comment by nebula-it** [comment]
Hey @MihkelBaranov ,
I did some digging into this and found [this](https://stackoverflow.com/questions/53239152/unexpected-end-of-file-with-pushing-items-to-an-array-with-jimp), hope you find it helpful.
Cheers
