### ISSUE TITLE
Error connecting to Database

### ISSUE THREAD

**Issue by juneflowers** [Wellenline/auddly-server#41]
I'm sure this is completely on my end, as someone relatively new to selfhosting/docker. I've cloned the compose and configured all the variables accordingly, I've created a postgres container(gave it a port as well) and configured it in the compose. Upon start I see this error. I've tried a few different things as DB_HOST all of which present an error.

postwave (the name of my database)
localhost
postgres

I can't seem to find solid information on what the DB_HOST variable should be set as. Can someone guide me in the right direction? I apologize for the dumb issue.

![image](https://user-images.githubusercontent.com/63337938/84492480-3a266500-ac74-11ea-8096-20b18b00dc6f.png)

**Comment by juneflowers** [comment]
Scratch that. Believe I figured it out(Open the database container in portainer and noticed it had it's own IP so I added that to the compose as the host) but I've encountered the next barrier to entry.
![image](https://user-images.githubusercontent.com/63337938/84495706-9c359900-ac79-11ea-8095-551d7458b774.png)
I set HOST=127.0.0.1:5000 and I see this. I also tried my actual 192.xxx.xx.xxx local ip and hit the same result. I'm using port 5000 and it's not bound to anything else. It's open in my firewall as well.

**Comment by juneflowers** [comment]
Logs are outputting these errors.


(node:25) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/music/이달의 소녀/이달의 소녀 오드아이써클/2017-09-21 - Max & Match (EP) [FLAC]/01-08 - Odd Front (1072kbps).flac'


    at FSWatcher.<computed> (internal/fs/watchers.js:169:26)


    at Object.watch (fs.js:1435:34)


    at createFsWatchInstance (/app/node_modules/chokidar/lib/nodefs-handler.js:118:15)


    at setFsWatchListener (/app/node_modules/chokidar/lib/nodefs-handler.js:165:15)


    at NodeFsHandler._watchWithNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:330:14)


    at NodeFsHandler._handleFile (/app/node_modules/chokidar/lib/nodefs-handler.js:360:23)


    at NodeFsHandler._addToNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:620:21)


(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15755)

**Comment by juneflowers** [comment]
I believe I fixed that too haha. I was expecting something to resolve in the browser but I misunderstood how this worked. I have come to what I believe to be the final error.

![image](https://user-images.githubusercontent.com/63337938/84498734-38ae6a00-ac7f-11ea-8738-03902e75b1cd.png)

**Comment by juneflowers** [comment]
Fixed it by switching to sqlite.
